### ISSUE TITLE
task is canceled error

### ISSUE THREAD

**Issue by BrannonKing** [pysco68/Pysco68.SignalR.HawkClient#2]
I'm attempting to try out this HawkClient. Each time I run I get a "task is canceled" error. Can you see anything wrong with this code?

``` csharp
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading;
using Microsoft.AspNet.SignalR;
using Microsoft.AspNet.SignalR.Client;
using Microsoft.Owin.Hosting;
using Microsoft.Owin.Hosting.Services;
using Microsoft.Owin.Hosting.Starter;
using Owin;
using Thinktecture.IdentityModel.Hawk.Core;
using Thinktecture.IdentityModel.Hawk.Core.Helpers;
using Thinktecture.IdentityModel.Hawk.Owin;
using Thinktecture.IdentityModel.Hawk.Owin.Extensions;

namespace TestHawk
{
    class Program
    {
        static void Main(string[] args)
        {
            var address = "http://localhost:19000";
            var server = new HubServer(address);

            var connection = new HubConnection(address);
            var proxy = connection.CreateHubProxy("MyHub");
            //connection.CookieContainer = new CookieContainer();
            var client = new HawkHttpClient(new Credential
            {
                Id = "dh37fgj492je",
                Algorithm = SupportedAlgorithms.SHA256,
                User = "Steve",
                Key = Convert.FromBase64String("wBgvhp1lZTr4Tb6K6+5OQa1bL9fxK7j8wBsepjqVNiQ=")
            });
            connection.Start(client).Wait();

            for (int i = 0; i < 10; i++)
            {
                var rand = proxy.Invoke<int>("GetRand").Result;
                Console.WriteLine("Rand: " + rand);
                Thread.Sleep(500);
            }

            connection.Dispose();

            if (Debugger.IsAttached)
                Console.ReadKey();

            server.Dispose();

        }
    }

    public class MyHub : Hub
    {
        public int GetRand()
        {
            return new Random().Next();
        }
    }

    public class HubServer : IDisposable
    {
        private readonly IDisposable _server;

        public HubServer(string interfaceAddress)
        {
            var services = (ServiceProvider) ServicesFactory.Create();

            var starter = services.GetService<IHostingStarter>();
            var options = new StartOptions(interfaceAddress);
            options.AppStartup = typeof(ServerStartup).AssemblyQualifiedName;
            _server = starter.Start(options);
        }

        public void Dispose()
        {
            _server.Dispose();
        }

        protected class ServerStartup
        {
            public virtual void Configuration(IAppBuilder app)
            {
                var credentialStorage = new List<Credential>()
                {
                    new Credential
                    {
                        Id = "dh37fgj492je",
                        Algorithm = SupportedAlgorithms.SHA256,
                        User = "Steve",
                        Key = Convert.FromBase64String("wBgvhp1lZTr4Tb6K6+5OQa1bL9fxK7j8wBsepjqVNiQ=")
                    }
                };

                var options = new Options
                {
                    ClockSkewSeconds = 60,
                    LocalTimeOffsetMillis = 0,

                    CredentialsCallback = id => credentialStorage.FirstOrDefault(c => c.Id == id),
                    ResponsePayloadHashabilityCallback = r => true,
                    //EnableServerAuthorization = false,
                    VerificationCallback = (request, ext) =>
                    {
                        if (String.IsNullOrEmpty(ext))
                            return true;

                        string name = "X-Request-Header-To-Protect";
                        return ext.Equals(name + ":" + request.Headers[name].First());
                    },
                };
                var hawkOptions = new HawkAuthenticationOptions(options);
                app.UseHawkAuthentication(hawkOptions);
                app.MapSignalR(new HubConfiguration
                {
                    EnableDetailedErrors = true,
                    EnableJavaScriptProxies = false,
                    EnableJSONP = false,
                });

                GlobalHost.HubPipeline.RequireAuthentication();
            }
        }
    }
}
```

**Comment by pysco68** [comment]
If you could post a detailed stack trace it'll be easier to figure out what is going wrong

**Comment by BrannonKing** [comment]
Here's the stack trace:

```
System.Threading.Tasks.TaskCanceledException occurred
  HResult=-2146233029
  Message=A task was canceled.
  Source=mscorlib
  StackTrace:
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at Thinktecture.IdentityModel.Hawk.Client.HawkValidationHandler.<SendAsync>d__0.MoveNext() in c:\etc\Dropbox\thinktecture\IdentityModel\source\Hawk\Client\HawkValidatingHandler.cs:line 37
  InnerException: 
```

**Comment by pysco68** [comment]
Well, I suspect that there is some issue with the connection to your SignalR hub. Does it fail on `connection.Start(client).Wait();` ?

Could you maybe try to hunt down where the TaskCancellationToken gets set?
